#===================================================================================================
# Description:
#   Message definition representing the RAPID data type "jointtarget" (joint position data).
#
# Note:
#   Please see the "Technical reference manual - RAPID Instructions, Functions and Data types"
#   for more details about RAPID data types.
#===================================================================================================

#---------------------------------------------------------------------------------------------------
# Message fields
#---------------------------------------------------------------------------------------------------

# Axis positions of the robot axes in degrees.
RobJoint robax

# The position of the external axes.
ExtJoint extax
