#===================================================================================================
# Description:
#   Message definition representing a subset of states of a mechanical unit defined
#   in an ABB robot controller system.
#===================================================================================================

#---------------------------------------------------------------------------------------------------
# Message fields
#---------------------------------------------------------------------------------------------------

# The mechanical unit's name.
string name

# The mechanical unit's activated/deactivated status.
bool activated
