#===================================================================================================
# Description:
#   Service definition for setting the value of a RAPID symbol (e.g. a variable) defined
#   in an ABB robot controller system.
#
# Note:
#   The RAPID symbol's new value must be in raw text format.
#===================================================================================================

#---------------------------------------------------------------------------------------------------
# Service request fields
#---------------------------------------------------------------------------------------------------

# Path to the targeted RAPID symbol.
RAPIDSymbolPath path

# New value (in raw text format) for the RAPID symbol.
string value

---

#---------------------------------------------------------------------------------------------------
# Service response fields
#---------------------------------------------------------------------------------------------------

# Service result indicating success/failure.
#
# Note: Refer to 'abb_robot_msgs/ServiceResult' for defined results.
ServiceResult result
