#===================================================================================================
# Description:
#   Service definition for triggering of a service where the response includes both
#   a numerical result code and a human readable message.
#===================================================================================================

#---------------------------------------------------------------------------------------------------
# Service request fields
#---------------------------------------------------------------------------------------------------

---

#---------------------------------------------------------------------------------------------------
# Service response fields
#---------------------------------------------------------------------------------------------------

# Service result indicating success/failure.
#
# Note: Refer to 'abb_robot_msgs/ServiceResult' for defined results.
ServiceResult result
